[[redirects]]
from = "/"
to = "/ua"
status = 302
force = true
conditions = {Country = ["uk"]}

[[redirects]]
from = "/"
to = "/ru"
status = 302
force = true
conditions = {Country = ["ru"]}
