[[redirects]]
from = "/index.html"
to = "/ua/index.html"
status = 302
force = true
conditions = {Language = ["uk"]}

[[redirects]]
from = "/index.html"
to = "/ru/index.html"
status = 302
force = true
conditions = {Language = ["ru"]}

[[redirects]]
from = "/index.html"
to = "/en/index.html"
status = 302
