[[redirects]]
from = "/"
to = "/ua"
status = 302
force = true
conditions = {Country = ["UA"]}

[[redirects]]
from = "/"
to = "/ru"
status = 302
force = true
conditions = {Country = ["RU"]}

[[redirects]]
from = "/"
to = "/en"
status = 302
force = true