[[redirects]]
from = "/index.html"
to = "/ua/index.html"
force = true
conditions = {Language = ["uk"]}

[[redirects]]
from = "/index.html"
to = "/ru/index.html"
force = true
conditions = {Language = ["ru"]}